line-length = 79
indent-width = 4

[lint]
select = [
	"F",
	"E",
	"C",
	"D",
]
ignore = [
	# All auto-fixable whitespace errors 
	"E2",

	# Remove only a few docstyle rules that I don't like
	"D203",
	"D212",
	"D413",
	"D415",
	"D416",
]
